### ISSUE TITLE
fix: Comment가 유지되지 않는 버그 픽스

### ISSUE THREAD

**Issue by ryong9rrr** [prgrms-fe-devcourse/FEDC2_LUVOOK_Jieun#127]
### ⏰ 개발 시작 날짜

2022년 6월 21일

### ⏰ 목표 완료 날짜

2022년 6월 21일

### 📃 작업 내용

코멘트를 남기고 모달 바깥으로 나가거나 새로고침을 했을 때 **코멘트 정보가 유지되지 않는** 버그를 고쳐봅니다.

**Comment by sukyeongh** [comment]
버그 수정하였습니다

**Comment by ryong9rrr** [comment]
close 하겠습니다! ㅎㅎ
